#!c:\users\bensaidfawzi\desktop\formation\formation-data scientist\chapitres\chapitre 7\flask\venv\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
